// <auto-generated />
using System;
using CGenius.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CGenius.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20240912150357_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CGenius.Models.Atendente", b =>
                {
                    b.Property<string>("CpfAtendente")
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.Property<string>("NomeAtendente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("PerfilAtendente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("CpfAtendente");

                    b.ToTable("Atendentes");
                });

            modelBuilder.Entity("CGenius.Models.Cliente", b =>
                {
                    b.Property<string>("CpfCliente")
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.Property<DateTime>("DtNascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<int>("IdScript")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("PerfilCliente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.HasKey("CpfCliente");

                    b.HasIndex("IdScript");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("CGenius.Models.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartamentoId"));

                    b.Property<string>("NomeDepartamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("DepartamentoId");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("CGenius.Models.Empregado", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Genero")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("EmpId");

                    b.ToTable("Empregados");
                });

            modelBuilder.Entity("CGenius.Models.Especificacao", b =>
                {
                    b.Property<int>("IdEspecificacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEspecificacao"));

                    b.Property<string>("CpfCliente")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.Property<int>("Dependentes")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("GastoMensal")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Interesses")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Profissao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<decimal>("RendaMensal")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("TipoCartaoCredito")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<bool>("ViajaFrequentemente")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("IdEspecificacao");

                    b.HasIndex("CpfCliente")
                        .IsUnique();

                    b.ToTable("Especificacoes");
                });

            modelBuilder.Entity("CGenius.Models.Plano", b =>
                {
                    b.Property<int>("IdPlano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlano"));

                    b.Property<string>("DescricaoPlano")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("NomePlano")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<decimal>("ValorPlano")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("IdPlano");

                    b.ToTable("Planos");
                });

            modelBuilder.Entity("CGenius.Models.Script", b =>
                {
                    b.Property<int>("IdScript")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdScript"));

                    b.Property<string>("DescricaoScript")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IdPlano")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdScript");

                    b.HasIndex("IdPlano");

                    b.ToTable("Scripts");
                });

            modelBuilder.Entity("CGenius.Models.Venda", b =>
                {
                    b.Property<int>("IdVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenda"));

                    b.Property<string>("CpfAtendente")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.Property<string>("CpfCliente")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.Property<int>("IdEspecificacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdPlano")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdScript")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdVenda");

                    b.HasIndex("CpfAtendente");

                    b.HasIndex("CpfCliente");

                    b.HasIndex("IdEspecificacao");

                    b.HasIndex("IdPlano");

                    b.HasIndex("IdScript");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("CGenius.Models.Cliente", b =>
                {
                    b.HasOne("CGenius.Models.Script", "Script")
                        .WithMany("Clientes")
                        .HasForeignKey("IdScript")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Script");
                });

            modelBuilder.Entity("CGenius.Models.Especificacao", b =>
                {
                    b.HasOne("CGenius.Models.Cliente", "Cliente")
                        .WithOne("Especificacao")
                        .HasForeignKey("CGenius.Models.Especificacao", "CpfCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CGenius.Models.Script", b =>
                {
                    b.HasOne("CGenius.Models.Plano", "Plano")
                        .WithMany("Scripts")
                        .HasForeignKey("IdPlano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("CGenius.Models.Venda", b =>
                {
                    b.HasOne("CGenius.Models.Atendente", "Atendente")
                        .WithMany("Vendas")
                        .HasForeignKey("CpfAtendente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGenius.Models.Cliente", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("CpfCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGenius.Models.Especificacao", "Especificacao")
                        .WithMany()
                        .HasForeignKey("IdEspecificacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGenius.Models.Plano", "Plano")
                        .WithMany("Vendas")
                        .HasForeignKey("IdPlano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGenius.Models.Script", "Script")
                        .WithMany("Vendas")
                        .HasForeignKey("IdScript")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendente");

                    b.Navigation("Cliente");

                    b.Navigation("Especificacao");

                    b.Navigation("Plano");

                    b.Navigation("Script");
                });

            modelBuilder.Entity("CGenius.Models.Atendente", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("CGenius.Models.Cliente", b =>
                {
                    b.Navigation("Especificacao")
                        .IsRequired();

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("CGenius.Models.Plano", b =>
                {
                    b.Navigation("Scripts");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("CGenius.Models.Script", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
